version: "3.9"

services:
  maps-app:
    container_name: maps-app
    image: maps-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./audio:/app/public/audio:ro
      - ./image:/app/public/image:ro
    environment:
      - NODE_ENV=production
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}
      - $API_BASE_URL=${API_BASE_URL}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
